[package]
name = "poc"
version = "0.1.0"
authors = ["timothee.arnauld1@gmail.com <timothee.arnauld1@gmail.com>"]

[lib]
name = "machine_learning"
crate-type = ["dylib"]
path = "src/lib.rs"

[dependencies]
rand = "0.4"
nalgebra = "0.14.0"
